-- Sector 3 autonomous pipeline: evals, pattern signals, opportunities, tracking columns

-- Migration A — arm3_tool_evals
CREATE TABLE IF NOT EXISTS public.arm3_tool_evals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tool_slug text NOT NULL REFERENCES public.arm3_tools(slug) ON DELETE CASCADE,
  eval_week date NOT NULL,
  signups_total integer DEFAULT 0,
  signups_this_week integer DEFAULT 0,
  usage_events integer DEFAULT 0,
  paying_users integer DEFAULT 0,
  revenue_usd numeric DEFAULT 0,
  score numeric DEFAULT 0,
  verdict text CHECK (verdict IN ('keep', 'adjust', 'scrap', 'pending')) DEFAULT 'pending',
  jb_decision text CHECK (jb_decision IN ('keep', 'adjust', 'scrap', NULL)),
  notes text,
  emailed_at timestamptz,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.arm3_tool_evals ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS arm3_tool_evals_tool_slug_idx ON public.arm3_tool_evals(tool_slug);
CREATE INDEX IF NOT EXISTS arm3_tool_evals_eval_week_idx ON public.arm3_tool_evals(eval_week);

-- Migration B — arm3_pattern_signals
CREATE TABLE IF NOT EXISTS public.arm3_pattern_signals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  signal_type text NOT NULL,
  value text NOT NULL,
  weight numeric DEFAULT 1.0,
  derived_from_evals jsonb DEFAULT '[]',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE (signal_type, value)
);

ALTER TABLE public.arm3_pattern_signals ENABLE ROW LEVEL SECURITY;

-- Migration D — pipeline tracking columns on arm3_opportunities
ALTER TABLE public.arm3_opportunities
  ADD COLUMN IF NOT EXISTS sector3_slug text UNIQUE,
  ADD COLUMN IF NOT EXISTS github_repo text,
  ADD COLUMN IF NOT EXISTS vercel_url text,
  ADD COLUMN IF NOT EXISTS launched_at timestamptz;

-- Migration C — three approved Sector 3 opportunities
INSERT INTO public.arm3_opportunities (
  name,
  description,
  market_signal,
  estimated_margin_pct,
  build_complexity,
  priority_score,
  status,
  flagged_for_jonny,
  notes
)
SELECT *
FROM (
  VALUES
    (
      'Outreach HQ',
      'AI-powered DM and cold email drafter with contact tracking. User pastes a name/niche/goal and gets a ready-to-send message with follow-up sequence.',
      'Validated internally on Match Fit trainer acquisition. High demand from solopreneurs, coaches, freelancers.',
      88::numeric,
      'low',
      95,
      'approved',
      true,
      'Sector 3 adaptation of Match Fit Outreach HQ. Strip Match Fit logic, make niche-agnostic. Target: anyone doing manual outreach.'
    ),
    (
      'Content Creator Rx',
      'AI content calendar + caption generator. User inputs their niche and audience, gets a full week of posts with captions, hashtags, and platform-specific formatting.',
      'Validated on Match Fit content calendar. Every small biz owner and creator needs this.',
      85::numeric,
      'low',
      90,
      'approved',
      true,
      'Sector 3 adaptation of Match Fit Content Calendar. Generic niche support. Target: creators, coaches, local biz owners.'
    ),
    (
      'Ad Sensei',
      'Ad performance tracker + AI insight engine. User logs their ad spend and results, AI surfaces patterns, waste, and recommendations in plain English.',
      'Validated on Match Fit ad tracker. Any small biz running Meta or Google ads has this pain.',
      82::numeric,
      'medium',
      85,
      'approved',
      true,
      'Sector 3 adaptation of Match Fit Ad Tracker. Platform-agnostic. Target: small biz owners running paid ads without an agency.'
    )
) AS v(
  name,
  description,
  market_signal,
  estimated_margin_pct,
  build_complexity,
  priority_score,
  status,
  flagged_for_jonny,
  notes
)
WHERE NOT EXISTS (
  SELECT 1 FROM public.arm3_opportunities o WHERE o.name = v.name
);

UPDATE public.arm3_opportunities SET sector3_slug = 'outreachhq' WHERE name = 'Outreach HQ' AND sector3_slug IS NULL;
UPDATE public.arm3_opportunities SET sector3_slug = 'creatorrx' WHERE name = 'Content Creator Rx' AND sector3_slug IS NULL;
UPDATE public.arm3_opportunities SET sector3_slug = 'adsensei' WHERE name = 'Ad Sensei' AND sector3_slug IS NULL;
