-- Seed ARM3 IT Lifecycle v2 initiatives into agent_dispatch (Hermes + AXON Dispatch Queue UI).
-- Briefs: docs/agent-dispatch/subagents/*.md

DELETE FROM public.agent_dispatch
WHERE source = 'jb-arm3-it-lifecycle-v2'
  AND code IN ('ARM3-1', 'IT-2', 'IT-3', 'AXON-4', 'NAV-5', 'NAV-6');

INSERT INTO public.agent_dispatch (
  code,
  title,
  owner,
  manager_chat,
  repo,
  status,
  priority,
  needs_jb_approval,
  action_type,
  dispatch_phrase,
  workflow_file,
  workflow_repo,
  depends_on,
  risk_tier,
  source,
  week_of,
  queued_by
)
VALUES
  (
    'ARM3-1',
    'ARM3 executive launch — M/W/F preview + summary + APPROVE/CHANGE/DENY',
    'manager',
    'manager',
    'northside-intelligence',
    'queued',
    1,
    true,
    'manager_phrase',
    'dispatch ARM3-1',
    NULL,
    'northsideventuresllc-sketch/northside-intelligence',
    ARRAY[]::text[],
    'major',
    'jb-arm3-it-lifecycle-v2',
    CURRENT_DATE,
    'NI Portal Manager'
  ),
  (
    'IT-2',
    'IT 90-day lifecycle — KEEP/TRIAL/REMOVE + Archived ITs (master only)',
    'manager',
    'manager',
    'northside-intelligence',
    'queued',
    2,
    true,
    'manager_phrase',
    'dispatch IT-2',
    NULL,
    'northsideventuresllc-sketch/northside-intelligence',
    ARRAY['ARM3-1']::text[],
    'major',
    'jb-arm3-it-lifecycle-v2',
    CURRENT_DATE,
    'NI Portal Manager'
  ),
  (
    'IT-3',
    'Monthly archive vault scan — revival IT report notifications',
    'manager',
    'manager',
    'northside-intelligence',
    'queued',
    3,
    false,
    'manager_phrase',
    'dispatch IT-3',
    NULL,
    'northsideventuresllc-sketch/northside-intelligence',
    ARRAY['IT-2']::text[],
    'minor',
    'jb-arm3-it-lifecycle-v2',
    CURRENT_DATE,
    'NI Portal Manager'
  ),
  (
    'AXON-4',
    'IT notification test panel — all IT report types in Test Mode',
    'manager',
    'manager',
    'northside-intelligence',
    'queued',
    4,
    false,
    'manager_phrase',
    'dispatch AXON-4',
    NULL,
    'northsideventuresllc-sketch/northside-intelligence',
    ARRAY['ARM3-1']::text[],
    'minor',
    'jb-arm3-it-lifecycle-v2',
    CURRENT_DATE,
    'NI Portal Manager'
  ),
  (
    'NAV-5',
    'Remove Admin Dashboard — AXON is sole master operator shell',
    'manager',
    'manager',
    'northside-intelligence',
    'queued',
    5,
    false,
    'manager_phrase',
    'dispatch NAV-5',
    NULL,
    'northsideventuresllc-sketch/northside-intelligence',
    ARRAY[]::text[],
    'minor',
    'jb-arm3-it-lifecycle-v2',
    CURRENT_DATE,
    'NI Portal Manager'
  ),
  (
    'NAV-6',
    'AXON nav dropdown — Home + Dash with access gating',
    'manager',
    'manager',
    'northside-intelligence',
    'queued',
    6,
    false,
    'manager_phrase',
    'dispatch NAV-6',
    NULL,
    'northsideventuresllc-sketch/northside-intelligence',
    ARRAY['NAV-5']::text[],
    'minor',
    'jb-arm3-it-lifecycle-v2',
    CURRENT_DATE,
    'NI Portal Manager'
  );
