-- ARM3 IT Lifecycle v2: launch notifications, archived tools, lifecycle columns

-- Launch review notifications (M/W/F preview gate)
CREATE TABLE IF NOT EXISTS public.arm3_it_launch_notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  opportunity_id bigint NOT NULL REFERENCES public.arm3_opportunities(id) ON DELETE CASCADE,
  tool_slug text NOT NULL,
  payload jsonb NOT NULL DEFAULT '{}',
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'approved', 'denied', 'changes_requested')),
  axon_notification_id text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS arm3_it_launch_notifications_opp_idx
  ON public.arm3_it_launch_notifications(opportunity_id);
CREATE INDEX IF NOT EXISTS arm3_it_launch_notifications_status_idx
  ON public.arm3_it_launch_notifications(status);

ALTER TABLE public.arm3_it_launch_notifications ENABLE ROW LEVEL SECURITY;

-- Archived ITs (master-only visibility enforced in portal)
CREATE TABLE IF NOT EXISTS public.arm3_archived_tools (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tool_slug text NOT NULL,
  name text NOT NULL,
  description text,
  snapshot jsonb NOT NULL DEFAULT '{}',
  metrics jsonb NOT NULL DEFAULT '{}',
  removed_at timestamptz NOT NULL DEFAULT now(),
  revival_eligible boolean NOT NULL DEFAULT true,
  last_revival_scan_at timestamptz,
  revival_score numeric,
  created_at timestamptz DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS arm3_archived_tools_slug_idx
  ON public.arm3_archived_tools(tool_slug);

ALTER TABLE public.arm3_archived_tools ENABLE ROW LEVEL SECURITY;

-- Opportunity review + executive summary
ALTER TABLE public.arm3_opportunities
  ADD COLUMN IF NOT EXISTS review_status text
    DEFAULT 'pending_review'
    CHECK (review_status IN ('pending_review', 'approved', 'denied', 'changes_requested')),
  ADD COLUMN IF NOT EXISTS preview_vercel_url text,
  ADD COLUMN IF NOT EXISTS executive_summary jsonb;

-- Tool lifecycle tracking
ALTER TABLE public.arm3_tools
  ADD COLUMN IF NOT EXISTS lifecycle_phase text
    DEFAULT 'preview'
    CHECK (lifecycle_phase IN ('preview', 'production', 'archived', 'trial')),
  ADD COLUMN IF NOT EXISTS lifecycle_locked_until timestamptz,
  ADD COLUMN IF NOT EXISTS trial_extension_until timestamptz,
  ADD COLUMN IF NOT EXISTS production_launched_at timestamptz,
  ADD COLUMN IF NOT EXISTS axon_build_ready boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS removal_scheduled_at timestamptz;

CREATE INDEX IF NOT EXISTS arm3_tools_lifecycle_phase_idx
  ON public.arm3_tools(lifecycle_phase);
CREATE INDEX IF NOT EXISTS arm3_tools_production_launched_at_idx
  ON public.arm3_tools(production_launched_at);
