import "server-only";
import { type ApiServicePreset } from "@/lib/bridgeai/presets";

export interface BridgeIntegrationBlueprint {
  recipeName: string;
  sourceService: string;
  destinationService: string;
  nodeCode: string;
  pythonCode: string;
  zapierRecipeJson: string;
  mcpToolSchema: string;
}

/**
 * Generates ready-to-run serverless bridge scripts and MCP schemas.
 */
export function generateIntegrationBlueprint(params: {
  source: ApiServicePreset;
  destination: ApiServicePreset;
  actionDescription: string;
}): BridgeIntegrationBlueprint {
  const { source, destination, actionDescription } = params;
  const recipeName = `${source.name} to ${destination.name} Bridge`;

  const nodeCode = `// Generated by Northside Intelligence BridgeAI
// Description: ${actionDescription}
import fetch from "node-fetch";

export async function executeBridge(payload: Record<string, unknown>) {
  const SOURCE_KEY = process.env.${source.serviceId.toUpperCase()}_API_KEY;
  const DEST_KEY = process.env.${destination.serviceId.toUpperCase()}_API_KEY;

  if (!SOURCE_KEY || !DEST_KEY) {
    throw new Error("Missing required environment variables for bridge execution.");
  }

  // 1. Process or Fetch from ${source.name}
  console.log("Ingesting event for ${source.name}...");

  // 2. Dispatch to ${destination.name}
  const destUrl = "${destination.baseUrl}${destination.commonEndpoints[0]?.path || ""}";
  const response = await fetch(destUrl, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "${destination.authHeaderName}": "${destination.authHeaderType === "Bearer" ? "Bearer " : ""}" + DEST_KEY,
    },
    body: JSON.stringify(payload),
  });

  if (!response.ok) {
    const errorBody = await response.text();
    throw new Error(\`Failed to dispatch to ${destination.name}: \${response.status} - \${errorBody}\`);
  }

  return await response.json();
}
`;

  const pythonCode = `# Generated by Northside Intelligence BridgeAI
# Description: ${actionDescription}
import os
import requests

def execute_bridge(payload: dict) -> dict:
    source_key = os.environ.get("${source.serviceId.toUpperCase()}_API_KEY")
    dest_key = os.environ.get("${destination.serviceId.toUpperCase()}_API_KEY")

    if not source_key or not dest_key:
        raise ValueError("Missing required environment API keys.")

    dest_url = "${destination.baseUrl}${destination.commonEndpoints[0]?.path || ""}"
    headers = {
        "Content-Type": "application/json",
        "${destination.authHeaderName}": f"${destination.authHeaderType == "Bearer" and "Bearer " or ""}{dest_key}",
    }

    res = requests.post(dest_url, json=payload, headers=headers, timeout=10)
    res.raise_for_status()
    return res.json()
`;

  const zapierRecipeJson = JSON.stringify(
    {
      title: recipeName,
      trigger: {
        app: source.serviceId,
        event: "new_item_created",
        auth: source.authHeaderType,
      },
      action: {
        app: destination.serviceId,
        event: destination.commonEndpoints[0]?.name || "create_record",
        endpoint: `${destination.baseUrl}${destination.commonEndpoints[0]?.path || ""}`,
      },
    },
    null,
    2
  );

  const mcpToolSchema = JSON.stringify(
    {
      name: `sync_${source.serviceId}_to_${destination.serviceId}`,
      description: actionDescription,
      parameters: {
        type: "object",
        properties: {
          recordId: { type: "string", description: "Identifier from " + source.name },
          dataPayload: { type: "object", description: "Fields to transfer to " + destination.name },
        },
        required: ["recordId", "dataPayload"],
      },
    },
    null,
    2
  );

  return {
    recipeName,
    sourceService: source.name,
    destinationService: destination.name,
    nodeCode,
    pythonCode,
    zapierRecipeJson,
    mcpToolSchema,
  };
}
